spring.application.name=kkdresses

# DATABASE
spring.datasource.url=${SPRING_DATASOURCE_URL}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME}

spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

# HIKARI
spring.datasource.hikari.maximum-pool-size=3

spring.datasource.hikari.data-source-properties.prepareThreshold=0

spring.datasource.hikari.data-source-properties.preparedStatementCacheQueries=0

spring.datasource.hikari.data-source-properties.preparedStatementCacheSizeMiB=0	